name: Java Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  local-run:
    runs-on: self-hosted

jobs:
  test-java-project:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Maven tests
        run: mvn clean test
